lens:
	parameters:
		r1: 1.50
		r2: Inf
		t: 0.10
		w: 1.00
		n: 1.53
	position:
		x: 0.000
		y: 0.000
		z: 0.380
	orientation:
		roll: 0.000
		pitch: 0.000
		yaw: 0.000
lens:
	parameters:
		r1: 0.75
		r2: -2.00
		t: 0.10
		w: 0.80
		n: 1.53
	position:
		x: 0.000
		y: 0.000
		z: 0.280
	orientation:
		roll: 0.000
		pitch: 0.000
		yaw: 0.000
lens:
	parameters:
		r1: 3.00
		r2: -0.60
		t: 0.01
		w: 0.80
		n: 1.53
	position:
		x: 0.000
		y: 0.000
		z: 0.200
	orientation:
		roll: 0.000
		pitch: 0.000
		yaw: 0.000
lens:
	parameters:
		r1: -0.60
		r2: Inf
		t: 0.01
		w: 0.80
		n: 1.53
	position:
		x: 0.000
		y: 0.000
		z: -0.200
	orientation:
		roll: 0.000
		pitch: 0.000
		yaw: 0.000
lens:
	parameters:
		r1: Inf
		r2: 1.00
		t: 0.15
		w: 0.80
		n: 1.53
	position:
		x: 0.000
		y: 0.000
		z: -0.285
	orientation:
		roll: 0.000
		pitch: 0.000
		yaw: 0.000
lens:
	parameters:
		r1: -3.00
		r2: 0.90
		t: 0.10
		w: 0.90
		n: 1.53
	position:
		x: 0.000
		y: 0.000
		z: -0.420
	orientation:
		roll: 0.000
		pitch: 0.000
		yaw: 0.000
lens:
	parameters:
		r1: 3.00
		r2: 5.00
		t: 0.07
		w: 1.00
		n: 1.53
	position:
		x: 0.000
		y: 0.000
		z: -0.520
	orientation:
		roll: 0.000
		pitch: 0.000
		yaw: 0.000
ray:
	origin:
		x: 0.200
		y: 0.000
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.400
		y: 0.000
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.141
		y: 0.141
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.283
		y: 0.283
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.000
		y: 0.200
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.000
		y: 0.400
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.141
		y: 0.141
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.283
		y: 0.283
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.200
		y: 0.000
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.400
		y: 0.000
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.141
		y: -0.141
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.283
		y: -0.283
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.000
		y: -0.200
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: -0.000
		y: -0.400
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.141
		y: -0.141
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.283
		y: -0.283
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.200
		y: -0.000
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
ray:
	origin:
		x: 0.400
		y: -0.000
		z: 2.000
	direction:
		x: 0.000
		y: 0.000
		z: -1.000
