lens:
  parameters:
    r1: -0.7
    r2: -0.7
    t: 0.3
    w: 1.0
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

lens:
  parameters:
    r1: 2.0
    r2: 2.0
    t: 0.3
    w: 1.0
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: 1.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

ray:
  origin:
    x: 0.4
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.2
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: 0.4
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: 0.2
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: -0.2
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: -0.4
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: -0.2
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: -0.4
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

