# Lens 1
lens:
  parameters:
    r1: 1.5
    r2: inf
    t: 0.1
    w: 1.0
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: 0.38
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# Lens 2
lens:
  parameters:
    r1: 0.75
    r2: -2.0
    t: 0.1
    w: 0.8
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: 0.28
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# Lens 3
lens:
  parameters:
    r1: 3.0
    r2: -0.6
    t: 0.01
    w: 0.8
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: 0.2
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# Lens 4
lens:
  parameters:
    r1: -0.6
    r2: inf
    t: 0.01
    w: 0.8
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: -0.2
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# Lens 5
lens:
  parameters:
    r1: inf
    r2: 1.0
    t: 0.15
    w: 0.8
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: -0.285
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# Lens 6
lens:
  parameters:
    r1: -3.0
    r2: 0.9
    t: 0.1
    w: 0.9
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: -0.42
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

# Lens 7
lens:
  parameters:
    r1: 3.0
    r2: 5.0
    t: 0.07
    w: 1.0
    n: 1.53
  position:
    x: 0.0
    y: 0.0
    z: -0.52
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0




ray:
  origin:
    x: 0.4
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.2
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: 0.4
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: 0.2
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: -0.2
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: -0.4
    y: 0.0
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: -0.2
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

ray:
  origin:
    x: 0.0
    y: -0.4
    z: 2.0
  direction:
    x: 0.0
    y: 0.0
    z: -1.0

