lens:
  parameters:
    r1: 1.0
    r2: 1.0
    t: 0.5
    w: 1.0
    n: 1.530
  position:
    x: 1.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

lens:
  parameters:
    r1: -1.0
    r2: -1.0
    t: 0.5
    w: 1.0
    n: 1.530
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
