function make_ray(origin, direction)
% Opens the scene file under 'lens_raytracer_3d/config/scene.yaml' and
% writes a new ray element.
% Input parameters:
%   - origin    : A 3-element vector specifying the origin of the ray.
%   - direction : A 3-element vector specifying the direction of the ray.

file_path = '../../config/';
scene_file = 'scene.yaml';

% Check if the scene file exists. If not, create it.
if exist([file_path, scene_file], 'file') ~= 2
    reset_scene_file;
end

% Open the scene file.
fh = fopen([file_path, scene_file], 'at');

% Append the lens information to the end of the file.
fprintf(fh, ['ray:'...
    '\n\torigin:'...
    '\n\t\tx: %.3f'...
    '\n\t\ty: %.3f'...
    '\n\t\tz: %.3f'...
    '\n\tdirection:'...
    '\n\t\tx: %.3f'...
    '\n\t\ty: %.3f'...
    '\n\t\tz: %.3f'...
    '\n'],...
    origin(1), origin(2), origin(3),...
    direction(1), direction(2), direction(3));

fprintf(1, ['\nWrote the following ray to %s:'...
     '\n\torigin:\n\t\tx: %.2f\n\t\ty: %.2f\n\t\tz: %.2f'...
     '\n\tdirection:\n\t\tx: %.2f\n\t\ty: %.2f\n\t\tz: %.2f\n'],...
     [file_path, scene_file],...
     origin(1), origin(2), origin(3),...
     direction(1), direction(2), direction(3));
 
% Close the scene file.
fclose(fh);